### ISSUE TITLE
Publish on Pypi?

### ISSUE THREAD

**Issue by pombredanne** [sassoftware/pymaven#6]
Any plans to publish this on Pypi? If is this something that you may not use heavily or depend on, I could take its maintenance over btw.

**Comment by wfscheper** [comment]
I'll see about getting a version with your PR up on PyPi.

As for maintaining pymaven, we're still ironing out how we want to manage our GitHub repositories. Also, I haven't forgotten about issue #4, I have most of the changes written and am just updating tests.

**Comment by wfscheper** [comment]
Published.

**Comment by pombredanne** [comment]
@wfscheper thanks my Lord! you rick!
