### ISSUE TITLE
Proposal: Enable testing on public CI (on Linux, macOSX and Windows)

### ISSUE THREAD

**Issue by pombredanne** [sassoftware/pymaven#7]
It would be great to have the tests run as part of each commit on CIs like Travis (Linux and macOS) and Appveyor (Windows).
I can contribute alright the manifests for that but the activation of the integration with this repo would have to be done by a repo admin.
Is this something you could contemplate? Alternatively I could enable this on a fork, but it would be best to have it on the main repo.

**Comment by wfscheper** [comment]
I definitely would like to get Travis integration working for pymaven. I'm about to push code to my fork that implements the file/string only Pom object. Do you mind basing your changes on that?

**Comment by wfscheper** [comment]
See PR #8.
